class FolderExistsException extends Exception

class ValidationException extends Exception

class FolderNotFoundException extends Exception

class BookmarkExistsException extends Exception

class BookmarkNotFoundException extends Exception
